### ISSUE TITLE
Webhooks raw data bug

### ISSUE THREAD

**Issue by leftys** [forwardemail/forwardemail.net#108]
Hello everyone,

first thanks for this great service, its very useful!

I set up a webhook and found out the raw attribute of the json data send to my webhooks contains malformed data. In FAQ it seems raw should look like this: 

```
"raw": "DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=forwardemail.net;\r\n q=dns/txt; ...
```

however in the actual http request they look like this
```
"raw":{"type":"Buffer","data":[65,82,67,45,83,101,97,108,58,32,105,61,49,59,32,97,61,114,115,97,45,115,104,
97,50,53,54,59,32,116,61,49,54,51,50,52,56,48,57,50,52,59,32,99,118,61,110,111,110,101,59,32,100,61,102,
111,114,119,97,114,100,101,109,97,105,108,...
```

This causes the webhook requests to be huge and often refused by services like requestbin.com with expcetions claiming request is too large (in this particular case `The body of the request is too large. Requests must be smaller than 100k (413)`.

**Comment by niftylettuce** [comment]
reviewing

**Comment by niftylettuce** [comment]
fix has been deployed, thanks!
