### ISSUE TITLE
Rethink bad tlds

### ISSUE THREAD

**Issue by veni-vidi-code** [forwardemail/forwardemail.net#111]
In

https://github.com/forwardemail/forwardemail.net/blob/2345862d9f3172220c1980395098c0d5fd76ab2e/config/index.js#L290

different bad tlds get declared. Trying to use one of them for emailforwarding will require a piad plan. Looking throught the given sources these lists do not correlate to them. E.g .email and .ga can not be found on one of the three lists while others that are on the lists are not on there. 

I would also like to see a way to be capable of using theme, as the only free available tlds out there are all on the list, so someone who would like to create a hobbypage could not use it. Maybe make it a one time payment at least in order of some kind of verification process.

**Comment by niftylettuce** [comment]
We're enforcing payment to ward off spammers and scammers that use these domains in mass/bulk for malicious purposes.
