### ISSUE TITLE
DKIM keys?

### ISSUE THREAD

**Issue by milindpatel63** [forwardemail/forwardemail.net#112]
Where do i get the dkim record that I need to add in my domain DNS txt record?
I am using cloudflare for dns

**Comment by niftylettuce** [comment]
If you send email with Gmail for instance, using Send Mail As, then it will automatically add a DKIM signature for you.  We don't add DKIM signatures as we simply forward messages, without altering them nor storing them.

**Comment by milindpatel63** [comment]
I have using this way to send newsletters via Mailchimp and also in my ghost blog to send users their login link...
So far emails are being sent, but till now I have received a few dmarc email from noreply-dmarc-support@google.com with a XML file....should I be concerned about something? will my domain get blacklisted or something?

**Comment by hagai-helman** [comment]
You may want to check out [Mailchimp's domain authentication instructions](https://mailchimp.com/help/set-up-email-domain-authentication/).
