### ISSUE TITLE
Password not strong enough

### ISSUE THREAD

**Issue by planetahuevo** [forwardemail/forwardemail.net#13]
Not sure how the system try to check if a password is strong or not, but 64 characters with 256bit key autogenerated password should be enough.
But it is not.
I suggest to change the way to check the passwords on the system. 

Thanks

**Comment by niftylettuce** [comment]
That's odd @planetahuevo - we use `strength`, and it looks like this issue is related. https://github.com/ruffrey/strength/issues/2

**Comment by planetahuevo** [comment]
Can you use something like https://github.com/mkopinsky/zxcvbn-php ?
https://lowe.github.io/tryzxcvbn/
It seems that strength has not been updated for a while.

**Comment by niftylettuce** [comment]
Yeah, was hooking in zxcvbn right now https://github.com/dropbox/zxcvbn

**Comment by planetahuevo** [comment]
The one I have linked is the most updated fork, have a look into that one and the issues with a long discussion about that. As far as I know, that one has evolved and it a little different (and better imho).

**Comment by niftylettuce** [comment]
We don't use PHP

**Comment by planetahuevo** [comment]
Oh, that is true. Sorry I forgot that link was for a php project. :)

**Comment by niftylettuce** [comment]
It's ok - if you find a better JS alternative let me know, I'm going to look into this more before integrating one solution vs. another

**Comment by planetahuevo** [comment]
I will,but that one is good enough as far as I know.
In any case, just force people to get 40 characters and you are good to go ;)

**Comment by niftylettuce** [comment]
Closed via https://github.com/forwardemail/forwardemail.net/pull/17 - I will be deploying this in the next release soon.
