### ISSUE TITLE
I can't receive mail

### ISSUE THREAD

**Issue by guoliyuan8899** [forwardemail/forwardemail.net#133]
error???

**Comment by niftylettuce** [comment]
Should be resolved now and emails should flow through.

**Comment by guoliyuan8899** [comment]
it'not work.i miss a lot of import email.

**Comment by guoliyuan8899** [comment]
hot to get them

**Comment by niftylettuce** [comment]
It will take time for them to flow through, but you will receive them soon.

**Comment by guoliyuan8899** [comment]
OK, but it seems that "forward" always breaks down recently. I hope it can be improved as soon as possible. I like "forward" very much. But recently it has let me miss a lot of emails.

**Comment by guoliyuan8899** [comment]
So wait a few hours and I'll get an email during the failure, right?

**Comment by niftylettuce** [comment]
Your emails should be flowing through and any email that was delayed this morning should be auto-retried.  Did you receive them yet?

**Comment by guoliyuan8899** [comment]
There are omissions.

**Comment by guoliyuan8899** [comment]
Not all the lost messages were received.
