### ISSUE TITLE
SPF Permanent Error: Two or more type TXT spf records found.

### ISSUE THREAD

**Issue by joelsteidl** [forwardemail/forwardemail.net#14]
421 SPF validation failed with result "permerror" and explanation "SPF Permanent Error: Two or more type TXT spf records found." - if you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net

Domain is https://www.csteachingtips.org/

I'd really appreciate help getting this figured out. I have the MX and SPF record in place.

**Comment by niftylettuce** [comment]
Looks like you've already resolved this as I do not see two SPF records.
