### ISSUE TITLE
Web interface: disable "bouncing" animation for notifications when user prefers reduced motion

### ISSUE THREAD

**Issue by iliana** [forwardemail/forwardemail.net#141]
Hi, I'm a user with a [condition that can cause animations to make me literally sick](https://webkit.org/blog/7551/responsive-design-for-motion/). I, and others like me, would appreciate if you can add a rule to your CSS to disable the fast rotating animation on the notification box.

This documentation describes the `prefers-reduced-motion` media query: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by niftylettuce** [comment]
@iliana thanks for sharing this!  the fix has been deployed on our website as of v0.4.26, please visit https://forwardemail.net and let us know if this fixes the issue for you, and makes your experience better! 🙇 🙏 ✨
