### ISSUE TITLE
your forwarded addresses will be publicly searchable

### ISSUE THREAD

**Issue by maravento** [forwardemail/forwardemail.net#147]
Hi. great project. We have published about you
https://www.maravento.com/2022/02/correos-con-dominio-propio-en-gmail.html

However, there is an unfinished part:
"If you are not on a paid plan, then **your forwarded addresses will be publicly searchable**"
https://forwardemail.net/es/faq#:~:text=If%20you%20are%20not%20on%20a%20paid%20plan%2C%20then%20your%20forwarded%20addresses%20will%20be%20publicly%20searchable

referring to this setting

"@", ".", or blank | 3600 | TXT | forward-email=user@gmail.com
-- | -- | -- | --

I would be grateful if you could explain this in more detail. Thanks in advanced

**Comment by politician** [comment]
It means anybody can see your forwarding settings and thus your email very easily by running the following in a shell:

```sh
dig txt maravento.com
```
![Screenshot 2022-02-22 at 09 52 16](https://user-images.githubusercontent.com/3155568/155054348-a7334626-40b3-4fc8-8d6f-ee3eb737a1eb.png)

I recommend you pay for the service, it supports this project as well as give you complete privacy.

**Comment by maravento** [comment]
mmm. that's too bad. I will post this warning to my audience, so they are forewarned. Thank you

**Comment by politician** [comment]
@maravento 👍
