### ISSUE TITLE
Registration: verification code never received

### ISSUE THREAD

**Issue by jamescridland** [forwardemail/forwardemail.net#149]
Discovered your website today, and it's exactly what I'm looking for; so I registered with the idea of becoming a paid user for a few different domains I use.

On registering, it asks me to

> Enter the verification code emailed to _(my correct email address)_

...but nothing ever appears; not in spam, or in the "all mail" view (of my Gmail, as it happens). I've asked for the verification code to be resent, which the website says it has done, but it hasn't.

For an email forwarding company, this is a little unnerving as a first experience... is this a bug with your system?

**Comment by jot** [comment]
I experienced the same problem today. I also signed up with a GMail address.

**Comment by niftylettuce** [comment]
This is temporary resolved, we had an issue with upstream provider (Postmark).

**Comment by niftylettuce** [comment]
Visit https://forwardemail.net again and should work fine for you

**Comment by jamescridland** [comment]
It now won't let me sign up, since it claims I have a "non-unique email". A request to reset my password (which I've not been able to set) doesn't work and sends me no reset link (or any email).

The email address is a Gmail one, starting james.cridland - would you please be able to wipe my details, and I'll (now not very confidently) start afresh?

**Comment by niftylettuce** [comment]
Yes we are still experiencing issues with Postmark, so forgot password emails aren't working at the moment.

@jamescridland I've removed your account, you can start fresh again

**Comment by jamescridland** [comment]
"Email is not unique"

**Comment by niftylettuce** [comment]
Sorry, try again @jamescridland.  I removed your account with the email address on your GitHub, not your Gmail.
