### ISSUE TITLE
How'd I add a DMARC reject policy ?

### ISSUE THREAD

**Issue by therealadityashankar** [forwardemail/forwardemail.net#15]
Hey !, I'm super naive to how emails work, but tolerate me here.

say I want to set a DMARC policy to only allow emails if they pass SPF checks, what would such a DMARC policy look like, is it possible to set such a DMARC policy ?

I recently learnt about DMARC policies and I want to ensure people can't send emails using my domain by spoofing

**Comment by niftylettuce** [comment]
You can't do this, DMARC passes if EITHER DKIM or SPF passes.  Read the official RFC spec for this.  I've updated our FAQ to be a little bit clearer / more visually refreshing.
