### ISSUE TITLE
Existing MX records

### ISSUE THREAD

**Issue by JonnyTech** [forwardemail/forwardemail.net#150]
When transferring to forwardemail.net and we change MX records, I assume that you keep a record of our previous MX records in order to correctly route future emails.

But what happens if one wants to leave forwardemail.net and go back to the original MX records?  Can we get the original MX records back?

Or if our email provider changes? How can we change the MX records that you forward the emails to?

**Comment by Slugger** [comment]
This service does not forward to alternate MX records.  It forwards to email addresses.  You tell this service where to forward your emails by setting up your aliases as TXT records in DNS.  The instructions are documented [here](https://forwardemail.net/en/faq#how-do-i-get-started-and-set-up-email-forwarding).

As long as your domain's MX records are pointing at this service, it will forward your email based on the TXT records you created.  If you don't want to use this service anymore, simply replace your domain's MX records, pointing them to an alternate mail handler.
