### ISSUE TITLE
catch-all vs catch-leftovers

### ISSUE THREAD

**Issue by mlsad3** [forwardemail/forwardemail.net#161]
Right now there are a lot of Google G Suite (Legacy) users that are needing to switch things around. Their situation (at least mine) is:
 - Several explicitly defined users (`userB@custom.com`, `userB@custom.com`, `userC@custom.com`) for other family members, each user has their own gmail account
 - Catch-all for the hundreds of random aliases (storeA@custom.com, bankB@custom.com) created over 15 years that all just get caught and go to a single gmail account (`userC@custom.com`)

It does not seem like this can be handled currently by forwardemail.net. With the given rules:
 - `forward-email=userA:userA@gmail.com` # userA@custom.com -> userA@gmail.com
 - `forward-email=userB:userB@gmail.com` # userB@custom.com -> userB@gmail.com
 - `forward-email=userC:userC@gmail.com` # userC@custom.com -> userC@gmail.com
 - `forward-email=userC@gmail.com` # Send everything else to userC@gmail.com

But based on the FAQ and a discussion with customer support, **Everything** (including all of `userA` and `userB`'s personal emails) will get sent to `userC@gmail.com`.

Can we add a "if nothing else matches" rule (catch-leftovers)? 
```
forward-email=?:userC@gmail.com  # Catch-leftovers, if all other rules do not match
```

**Comment by mlsad3** [comment]
A workaround I think could work is to register two domains (`custom2.com` and `custom.com`).

`custom.com` Rules:
```
forward-email=userA:userA@gmail.com
forward-email=userB:userB@gmail.com
forward-email=userC:userC@gmail.com
forward-email=userC@custom2.com
```

`custom2.com` Rules:
```
forward-email=!userA
forward-email=!userB
forward-email=userC@gmail.com
```

But this doesn't seem as elegant as having "catch-leftovers" natively supported (not sure how many people would want to register a second domain to just do this)

**Comment by mlsad3** [comment]
Okay thanks @Slugger for the confirmation. I never signed up for forwardemail, since when I asked customer support regarding this, they said otherwise. But if it works for you, then I'm sure it will work for me. Thanks!

**Comment by schultzter** [comment]
This is a great explanation, it should be added to the FAQ
