### ISSUE TITLE
How to: Translate to German 

### ISSUE THREAD

**Issue by pke** [forwardemail/forwardemail.net#2]
Thanks for setting this service up and open source it.
I'd like to add some translations as PRs if possible.
Where do I start best?
The website shows CN and ES translations but I can't seem to find them here in the repo.

**Comment by niftylettuce** [comment]
Basically the `locales/` folder has `en.json` (EN), `zh.json` (CH), and `es.json` (Spanish).  I need to remove them from the `.gitignore` and push them up as part of a pre-commit process.  Here are the files from the server if you wanted to do some translations in the meanwhile that I could upload until these are committed directly to GitHub `locales` dir:

[locales.zip](https://github.com/forwardemail/forwardemail.net/files/4068168/locales.zip)

**Comment by niftylettuce** [comment]
If you wanted to dig deeper, we have a job that runs and constantly re-builds and updates the localizations: <https://github.com/forwardemail/forwardemail.net/blob/master/queues/translate-phrases.js>

**Comment by pke** [comment]
thanks. I was checking the source but could not find the locales folder.

**Comment by pke** [comment]
Hmm things like `):` and `3` are in the translations file too. I know how they ended up there but is there really no better way?

**Comment by niftylettuce** [comment]
The culprit is here mainly:
https://github.com/niftylettuce/mandarin/issues/1

It parses the markdown files and translates them, and I'm using remark, and
just parsing all text blocks, but it needs further refined to parse
sentences, which I'm not sure how to do with the sentence (context of the
sentence) and everything.

**Comment by niftylettuce** [comment]
PR welcome to this file https://github.com/forwardemail/forwardemail.net/blob/master/locales/de.json

**Comment by pke** [comment]
Will do as time permits, thanks!
