### ISSUE TITLE
Can't open domain settings. Error in /var/www/production/....

### ISSUE THREAD

**Issue by lucafont2** [forwardemail/forwardemail.net#22]
When i try to enter domain settings, this popup displays:

`/var/www/production/source/app/views/my-account/domains/retrieve.pug:72 70| h5.card-header= t('Enhanced Protection Verification Record') 71| .card-body > 72| p!= t('Please ensure that a TXT record exists for %s with the following value:', domain.name) 73| .input-group 74| input(type='text', readonly, value=`${config.recordPrefix}-site-verification=${domain.verification_record}`).form-control#verification-record 75| .input-group-append [sprintf] unexpected placeholder`

And i can't enter the page.

**Comment by niftylettuce** [comment]
Resolved

🎉 I just completely released a completely overhauled FAQ, Features, and My Domain pages with lots of improvements!
https://forwardemail.net

**Comment by niftylettuce** [comment]
Ref: https://github.com/forwardemail/forwardemail.net/releases/tag/v0.1.25
