### ISSUE TITLE
FAQs Page - Changes Needed

### ISSUE THREAD

**Issue by alicegomaird** [forwardemail/forwardemail.net#35]
* Add step before step 6 called "Double-check and make sure you have the following MX and TXT records set in your registrar's DNS management page:"

| Name/Host/Alias | TTL | Record Type | Priority | Value/Answer/Destination |
| ----------------- | ---- | ------------ | ------- | -------------------------- |
| @ or leave blank | 3600 | MX | 10 | mx1.forwardemail.net | 
| @ or leave blank | 3600 | MX | 20 | mx2.forwardemail.net |

| Name/Host/Alias | TTL | Record Type | Value/Answer/Destination |
| ----------------- | ---- | ------------ | -------------------------- |
| @ or leave blank | 3600 | TXT | Option A, B, C, D, E, or F |
| @ or leave blank | 3600 | TXT | v=spf1 a mx include:spf.forwardemail.net -all |

* After this added step, please add this step below
  *  "After you've saved all your changes, please purge your cache at https://1.1.1.1/purge-cache/"
    *  Tip: Make sure you purge all MX, TXT, and DNS records

**Comment by niftylettuce** [comment]
closing as kind of redundant and they are already steps, the purge cache part is listed on the page for forwarding

im also overhauling the ui in near future for onboarding/faq stuff
