### ISSUE TITLE
Main Page - Changes Needed

### ISSUE THREAD

**Issue by alicegomaird** [forwardemail/forwardemail.net#36]
* Change "We don't store logs nor emails." to "We do not keep logs nor store emails." 
  * Make sure this change is made everywhere that phrase is shown
* "Stay Protected" button should be blue and in all caps to stand out and call attention for action (similar to the "SIGN UP FOR FREE" button
* Under "100% open-source" section make these changes:
  * change "we don't store logs never read emails" to "we do not keep logs, never read nor store emails"
* Our feature buttons should be blue instead of grey when you hover over it (this is to keep in line with branding and make blue associated with call-to-action buttons)
![Screen Shot 2020-06-11 at 9 35 09 PM](https://user-images.githubusercontent.com/66087258/84455541-944f0800-ac2b-11ea-868f-a9a744df3174.png)
* "View source code" should be blue and in all caps as well
* If possible, make the "Our Numbers" section add up like a stopwatch to final numbers

**Comment by niftylettuce** [comment]
fixed verbiage, all others are holding off for now, good suggestions though
