### ISSUE TITLE
Our Story Page - Changes Needed

### ISSUE THREAD

**Issue by alicegomaird** [forwardemail/forwardemail.net#38]
* Remove "TLDR;"
*Make the layout the same as the home page
  * Include dark grey boxes, like the one shown below (perhaps for the Foreward)
    * Change "Foreward" to "Introduction"
![Screen Shot 2020-06-11 at 9 48 52 PM](https://user-images.githubusercontent.com/66087258/84456210-6ec2fe00-ac2d-11ea-871a-b33bd8eaf6be.png)
* Make a timeline for the history where you can hover over the important dates and read about them (will look more organized and actually show our progress)

**Comment by niftylettuce** [comment]
no timeline for now, removed tldr at least
