### ISSUE TITLE
Unlimited domains (yes, we offer unlimited domains on all plans)

### ISSUE THREAD

**Issue by svrooij** [forwardemail/forwardemail.net#44]
If I check the pricing page, it seems like the "Enhanced protection" costs $3 per month. But if I switch a domain to this it seems like it's per domain.

That wasn't clear to me upfront.

**Comment by niftylettuce** [comment]
Yeah sorry about that - I'm working on a new UI that will resolve all confusion.

**Comment by svrooij** [comment]
a "per domain" would solve that.

Any plans for a multi domain package? And is it possible to get invoices when you finish the beta?

**Comment by niftylettuce** [comment]
It's unlimited domains with $3/mo.  Not per domain.  And yes, invoices and billing will be super nice with exports and PDF's and emails and all.  It's really slick you're going to love it.

**Comment by svrooij** [comment]
If it's unlimited domains for $3 a month, why do I have to upgrade every single domain separately?

Want me to have a look at the new UI (as a fresh pair of eyes)?

**Comment by niftylettuce** [comment]
It's confusing right now because I originally was going to be like everyone else and charge per domain.  I changed my mind _after_ and that's why it's a bit off right now.  Will be fixed up very soon.

**Comment by niftylettuce** [comment]
This has been clarified on the new pricing page updates, and will be further clarified on new UI flow.
