### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by aaronstuder** [forwardemail/forwardemail.net#6]
![image](https://user-images.githubusercontent.com/459982/73849416-e2747a80-47f7-11ea-9852-0b79b2115ae6.png)

**Comment by niftylettuce** [comment]
You signed in with GitHub or Google, you need to sign in with your original auth provider and then set a password on the account.

**Comment by shaunwarman** [comment]
Error message updated in #42

**Comment by niftylettuce** [comment]
Deployed already
