### ISSUE TITLE
[question] is it bad if I disable FE Spam filters and use Gmail spam filters? (does it harm your smtp servers?)

### ISSUE THREAD

**Issue by Bestulo** [forwardemail/forwardemail.net#75]
I have an address registered with forwardemail and disabled spam filter. I plan to use it to register to forums.

I disabled spam filters because I want all the emails to come! I don't want to get legitimate emails not delivered to me because they were misidentified as spam. My problem with FE spam filter is there is no folder where I can see what emails were caught!

I see 2 potential problems.
1. If spam does come from my domain, gmail may report **my domain** as a spam sender.
2. If spam does come from my domain, gmail may report **forwardemail.net smtp servers** as spam senders.

Is this a real problem or am I imagining things? Am I harming FE by disabling spam filters? What choices do I have if I want everything to be delivered but don't want to harm either FE or my domain?

**Comment by niftylettuce** [comment]
No it's fine, we use ARC.

**Comment by niftylettuce** [comment]
(you can disable all of them, they're actually all turned off right now as I need to finish optimizations)

**Comment by Bestulo** [comment]
What's ARC?

**Comment by Bestulo** [comment]
Nevermind I googled it.

**Comment by niftylettuce** [comment]
Yeah. Imagine you have an envelope in the mail.  Without ARC anyone could write over the return address or where it's going to, or change the stamp.  ARC basically laminates the envelope so people can't alter it, and we laminate and verify where it's coming from and all.
