### ISSUE TITLE
"100% open-source"

### ISSUE THREAD

**Issue by Aspie96** [forwardemail/forwardemail.net#76]
The website claims 100% open-source, which the server-side is not (source-available, yes, but not open source).

The license is clearly not open source. Which is ok, just be honest about it because the website is confusing

I suggest to correct the website.

**Comment by niftylettuce** [comment]
If you bothered to look at our GitHub organization, you would see the server-side is all available.

https://github.com/forwardemail

https://github.com/forwardemail/free-email-forwarding

**Comment by Aspie96** [comment]
Thanks, my bad!

I apologize.

**Comment by niftylettuce** [comment]
Not a problem at all 😄  Thank you! @Aspie96

**Comment by planetahuevo** [comment]
Hi! 
Your license is not Open Source but  Source Available, which is not the same.
https://en.wikipedia.org/wiki/Source-available_software 
Which again is fine, I prefer if you change the wording on your site, as I was confused but apart from that it is your code. :) 

I also was reading the license and I saw that you are using some parts of code that is GPL3 (for example https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/LICENSE) , but your license is not compatible with that. 

Did you check that all your code and third party software are compatible with the license you are using? 

Thanks!

**Comment by planetahuevo** [comment]
Hi!
Your license is not Open Source but Source Available, which is not the same.
https://en.wikipedia.org/wiki/Source-available_software
Which again is fine, I prefer if you change the wording on your site, as I was confused but apart from that it is your code. :)

I also was reading the license and I saw that you are using some parts of code that is GPL3 (for example https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/LICENSE) , but your license is not compatible with that.

Did you check that all your code and third party software are compatible with the license you are using?

Thanks!
