### ISSUE TITLE
[feat] Encrypted DNS records

### ISSUE THREAD

**Issue by lholota** [forwardemail/forwardemail.net#80]
I have been using the freeplan for quite a while and the only thing I would like to improve a bit is the fact that the configuration is exposed in the TXT records in plain text. I know the paid plan has a feature that fixes this, but there is another option:

Store the configuration in publicly exposed DNS records, but in an encrypted form. The DNS record could then look for example like this:

|Name/Host/Alias | TTL | Record Type | Value/Answer/Destination|
|-- | -- | -- | --|
|@ or leave blank | 3600 | TXT | forward-email=enc:<encrypted-value>|

## Option 1 - Symmetric algorithm
Given that the key for symmetric encryption must be kept secret, the encryption would have to be done by the site. The user would sign into their account in forwardemail.net, enter the desired value and the website would return an encrypted version of the value. User would then just copy-paste this value into their DNS configuration.

## Option 2 - Asymmetric algorithm
In this case, the public key could be really publicly exposed and therefore the encryption could be done by the users manually, it can be done on users' machines, it could be used in automated scripts etc. Decryption of asymmetrically encrypted data is usually more complex though.

I know this means development of new functionality (e.g. encryption key storage), but it does not require additional storage which would grow with the number of users (you can just rotate the keys every couple of weeks/months and the keys can be shared) and it does not require additional network calls when processing a forwarded e-mail.

Another benefit of this feature is that DNS records for webhooks could then also contain shared secret for signing the payload (like GitHub uses for their webhooks) which makes security the webhook consuming endpoint a lot simpler.

I case you decided to give this one a try, I am happy to assist.

**Comment by shaunwarman** [comment]
Thanks @lholota - This is a great idea! One issue I'm trying to think through is the need for cert expiration management and along side that, the ability to properly mitigate failed emails during a time when keys need to be rotated either on our side (invalidating the TXT record entry) or on client side where the user needs to rotate their keys and update the TXT record.

**Comment by levifig** [comment]
Isn't this the whole point of the "Enhanced Protection" plan? You pay $3/mo for **unlimited** domains if you care for this level of privacy, which I feel is a fair price for a super flexible and powerful service like this… ¯\\\_(ツ)_/¯

**Comment by securingmom** [comment]
>  configuration is exposed in the TXT records in plain text

This is not clearly explained on the website.  Not only ought it be stated during signup not-burried in a link, but the impact ought be explained.  DNS is harvested for any number of privacy demeaning free services since 2008.  Free users can ironically expect spam.

**Comment by levifig** [comment]
@securingmom Like stated above, `ForwardEmail` seems to very clearly position itself as an open-source **product**, free as in _speech_, not as in _beer_. It offers a free (as in _beer_) plan, for simple use cases, and a paid one, that finances the service.

Most registrars and/or DNS providers have email forwarding services. Some free, some paid. If you need a free service, you can pick a registrar/DNS provider that offers that service. Same with WHOIS privacy: some registrars offer that "free of charge", some charge for it.

I'm honestly not sure why you downvoted my comment, which was a direct reply to this thread.
Regardless, have a great day. 👍

**Comment by niftylettuce** [comment]
I will be supporting a legacy free version that's purely DNS based and also supporting a new version for free in the future that uses our alias manager.

**Comment by securingmom** [comment]
@levifig 

I understand the distinction.  I am merely requesting Informed Consent.  People ought understand the dig exposure concerns prior to participation.

Running my own private instance would be put on hold until the exposure of secret address can be eliminated.  For more than casual exploration I would buy a club TLD for catch-all plus sieve, or IMAP with local client rules.
