### ISSUE TITLE
Forward mails to other host and port with same domain

### ISSUE THREAD

**Issue by pbek** [forwardemail/forwardemail.net#87]
Hi there, thank you for this great service!

Is it possible to forward emails to another host (in conjunction with the forward-email-port setting) without rewriting the domain? If I am using `forward-email=mx2.domain.com` for my domain `domain.com`, then emails like test@domain.com will be rewritten to test@mx2.domain.com, but I want them stay the same.

Scenario: using forwardemail as backup mx to a host with blocked port 25

Thank you very much!

**Comment by pbek** [comment]
Move to https://github.com/forwardemail/free-email-forwarding/issues/242.

**Comment by niftylettuce** [comment]
So you're asking if `forward-email=someotherdomain.com` will work in combination with `forward-email-port`?  Yes.  Emails don't get rewritten (we don't rewrite FROM/TO or anything, just the envelope/MAILFROM in SMTP).
