### ISSUE TITLE
informed consent missing

### ISSUE THREAD

**Issue by securingmom** [forwardemail/forwardemail.net#88]
>  configuration is exposed in the TXT records in plain text

This is not clearly explained on the website.  Not only ought it be stated during signup not-burried in a link, but the impact ought be explained.  DNS is harvested for any number of privacy demeaning free services since 2008.  Free users can ironically expect spam.

**Comment by niftylettuce** [comment]
Yes, it is explained on the pricing page.  Also it is common knowledge that DNS is public record.  I will be supporting a legacy free version that's purely DNS based and also supporting a new version for free in the future that uses our alias manager.
