### ISSUE TITLE
Cancel Subscription throws  500 internal server error

### ISSUE THREAD

**Issue by nyarla** [forwardemail/forwardemail.net#93]
I trying to one-time cancel subscription for changing payment mehod,
but I got `500 internal server error` with this message:

> Cannot read property 'paypalSubscriptionID' of undefined

# Background

Today (2021-01-17 JST), I want change subscription method from Paypal to Credit card (via Revolut),
but I cannot found changing to payment method on forwardemail.net.

So, I think:

> Maybe, I'm enable to change of payment method,
> one-time cancel subscription, and re-subscribe to different payment method...?

and trying that, but I got 500 error.

And note, I'm ok that I cannot change to payment method at today or later,
but that error probablly makes trouble another people I think.

# How to reproduce

1. Go to [billing page](https://forwardemail.net/en/my-account/billing) on My account
2. Click `Cancel Subscription` button and `OK` on confirm dialog
3. I got `500 internal server error` with `Cannot read property 'paypalSubscriptionID' of undefined`

# Environments

* Windows 10 Pro 20H2  (Japanese Edition)
* Firefox 84.0.2 by PortableApps (Japanese locale)
* Currenly, My subscription method is payment at monthly via Paypal

and,

* I got this error both Normal and Private mode on Firefox
* My main locale is Japanese, but I used by English on forwardemail.net
* When I trying to one-time cancel subscription, I registered two own domain my account.

**Comment by niftylettuce** [comment]
This is fixed and is being deployed now, thank you.
