### ISSUE TITLE
Privacy issue: Can fetch all private email addresses by DNS lookup

### ISSUE THREAD

**Issue by ramondeklein** [forwardemail/forwardemail.net#98]
It's pretty easy to create a DNS scraper that checks if the top-level MX records are pointing to `mx1.forwardemail.net` and `mx2.forwardemail.net`. In these cases we can run another DNS query to obtain all the aliases. When you type: `dig TXT example.com`, then it would show all the email forwardings and expose the private email address.

This could easily be prevented by creating a secret during domain registration with forwardemail.net. Instead of looking up the TXT record on the root-level, it could check for the secret TXT record. Both forwardemail.net knows about this secret and the user that registered the email domain. Nobody else knows the secret and therefore can't find the forwarding records and the private email addresses stay private.

The only catch is when AXFR is configured incorrectly and accepts requests from any IP addresses (which is flawed anyway). Most cloud providers (i.e. Azure DNS, AWS Route53) don't support AXFR at all, so this is hardly a problem in real-life.

**Comment by MaanasNair** [comment]
Ooh yeah, true

**Comment by niftylettuce** [comment]
You can sign up for the Enhanced Protection plan which does this.

https://forwardemail.net/pricing

**Comment by ramondeklein** [comment]
@niftylettuce Thanks for pointing out to the enhanced protection plan. I do think this "drawback" of the free plan should be marked more clearly (could also improve conversion to a paid plan). Most people won't realize that their private email addresses are exposed via this service. For my purposes, this isn't a big deal, but it might for some people.
